race_list = [
  "Gulf Air Bahrain Grand Prix",
  "STC Saudi Arabian Grand Prix",
  "Heineken Australian Grand Prix",
  "Rolex Gran Premio Del Made In Italy E Dell'Emilia-Romagna",
  "Crypto.com Miami Grand Prix",
  "Pirelli Gran Premio De España",
  "Grand Prix De Monaco",
  "Azerbaijan Grand Prix",
  "Grand Prix Du Canada",
  "Lenovo British Grand Prix"
]

race_drivers_list = [
  [2022, race_list[0], "Mercedes-AMG Petronas F1 Team", "HAM"],
  [2022, race_list[0], "Mercedes-AMG Petronas F1 Team", "RUS"],
  [2022, race_list[0], "Oracle Red Bull Racing", "VER"],
  [2022, race_list[0], "Oracle Red Bull Racing", "PER"],
  [2022, race_list[0], "Scuderia Ferrari", "LEC"],
  [2022, race_list[0], "Scuderia Ferrari", "SAI"],
  [2022, race_list[0], "McLaren F1 Team", "NOR"],
  [2022, race_list[0], "McLaren F1 Team", "RIC"],
  [2022, race_list[0], "BWT Alpine F1 Team", "OCO"],
  [2022, race_list[0], "BWT Alpine F1 Team", "ALO"],
  [2022, race_list[0], "Scuderia AlphaTauri", "GAS"],
  [2022, race_list[0], "Scuderia AlphaTauri", "TSU"],
  [2022, race_list[0], "Aston Martin Aramco Cognizant F1 Team", "STR"],
  [2022, race_list[0], "Aston Martin Aramco Cognizant F1 Team", "HUL"],
  [2022, race_list[0], "Williams Racing", "ALB"],
  [2022, race_list[0], "Williams Racing", "LAT"],
  [2022, race_list[0], "Alfa Romeo F1 Team Orlen", "BOT"],
  [2022, race_list[0], "Alfa Romeo F1 Team Orlen", "ZHO"],
  [2022, race_list[0], "Haas F1 Team", "MAG"],
  [2022, race_list[0], "Haas F1 Team", "MSC"],

  [2022, race_list[1], "Mercedes-AMG Petronas F1 Team", "HAM"],
  [2022, race_list[1], "Mercedes-AMG Petronas F1 Team", "RUS"],
  [2022, race_list[1], "Oracle Red Bull Racing", "VER"],
  [2022, race_list[1], "Oracle Red Bull Racing", "PER"],
  [2022, race_list[1], "Scuderia Ferrari", "LEC"],
  [2022, race_list[1], "Scuderia Ferrari", "SAI"],
  [2022, race_list[1], "McLaren F1 Team", "NOR"],
  [2022, race_list[1], "McLaren F1 Team", "RIC"],
  [2022, race_list[1], "BWT Alpine F1 Team", "OCO"],
  [2022, race_list[1], "BWT Alpine F1 Team", "ALO"],
  [2022, race_list[1], "Scuderia AlphaTauri", "GAS"],
  [2022, race_list[1], "Scuderia AlphaTauri", "TSU"],
  [2022, race_list[1], "Aston Martin Aramco Cognizant F1 Team", "STR"],
  [2022, race_list[1], "Aston Martin Aramco Cognizant F1 Team", "HUL"],
  [2022, race_list[1], "Williams Racing", "ALB"],
  [2022, race_list[1], "Williams Racing", "LAT"],
  [2022, race_list[1], "Alfa Romeo F1 Team Orlen", "BOT"],
  [2022, race_list[1], "Alfa Romeo F1 Team Orlen", "ZHO"],
  [2022, race_list[1], "Haas F1 Team", "MAG"],
  [2022, race_list[1], "Haas F1 Team", "MSC"],

  [2022, race_list[2], "Mercedes-AMG Petronas F1 Team", "HAM"],
  [2022, race_list[2], "Mercedes-AMG Petronas F1 Team", "RUS"],
  [2022, race_list[2], "Oracle Red Bull Racing", "VER"],
  [2022, race_list[2], "Oracle Red Bull Racing", "PER"],
  [2022, race_list[2], "Scuderia Ferrari", "LEC"],
  [2022, race_list[2], "Scuderia Ferrari", "SAI"],
  [2022, race_list[2], "McLaren F1 Team", "NOR"],
  [2022, race_list[2], "McLaren F1 Team", "RIC"],
  [2022, race_list[2], "BWT Alpine F1 Team", "OCO"],
  [2022, race_list[2], "BWT Alpine F1 Team", "ALO"],
  [2022, race_list[2], "Scuderia AlphaTauri", "GAS"],
  [2022, race_list[2], "Scuderia AlphaTauri", "TSU"],
  [2022, race_list[2], "Aston Martin Aramco Cognizant F1 Team", "STR"],
  [2022, race_list[2], "Aston Martin Aramco Cognizant F1 Team", "VET"],
  [2022, race_list[2], "Williams Racing", "ALB"],
  [2022, race_list[2], "Williams Racing", "LAT"],
  [2022, race_list[2], "Alfa Romeo F1 Team Orlen", "BOT"],
  [2022, race_list[2], "Alfa Romeo F1 Team Orlen", "ZHO"],
  [2022, race_list[2], "Haas F1 Team", "MAG"],
  [2022, race_list[2], "Haas F1 Team", "MSC"],

  [2022, race_list[3], "Mercedes-AMG Petronas F1 Team", "HAM"],
  [2022, race_list[3], "Mercedes-AMG Petronas F1 Team", "RUS"],
  [2022, race_list[3], "Oracle Red Bull Racing", "VER"],
  [2022, race_list[3], "Oracle Red Bull Racing", "PER"],
  [2022, race_list[3], "Scuderia Ferrari", "LEC"],
  [2022, race_list[3], "Scuderia Ferrari", "SAI"],
  [2022, race_list[3], "McLaren F1 Team", "NOR"],
  [2022, race_list[3], "McLaren F1 Team", "RIC"],
  [2022, race_list[3], "BWT Alpine F1 Team", "OCO"],
  [2022, race_list[3], "BWT Alpine F1 Team", "ALO"],
  [2022, race_list[3], "Scuderia AlphaTauri", "GAS"],
  [2022, race_list[3], "Scuderia AlphaTauri", "TSU"],
  [2022, race_list[3], "Aston Martin Aramco Cognizant F1 Team", "STR"],
  [2022, race_list[3], "Aston Martin Aramco Cognizant F1 Team", "VET"],
  [2022, race_list[3], "Williams Racing", "ALB"],
  [2022, race_list[3], "Williams Racing", "LAT"],
  [2022, race_list[3], "Alfa Romeo F1 Team Orlen", "BOT"],
  [2022, race_list[3], "Alfa Romeo F1 Team Orlen", "ZHO"],
  [2022, race_list[3], "Haas F1 Team", "MAG"],
  [2022, race_list[3], "Haas F1 Team", "MSC"],

  [2022, race_list[4], "Mercedes-AMG Petronas F1 Team", "HAM"],
  [2022, race_list[4], "Mercedes-AMG Petronas F1 Team", "RUS"],
  [2022, race_list[4], "Oracle Red Bull Racing", "VER"],
  [2022, race_list[4], "Oracle Red Bull Racing", "PER"],
  [2022, race_list[4], "Scuderia Ferrari", "LEC"],
  [2022, race_list[4], "Scuderia Ferrari", "SAI"],
  [2022, race_list[4], "McLaren F1 Team", "NOR"],
  [2022, race_list[4], "McLaren F1 Team", "RIC"],
  [2022, race_list[4], "BWT Alpine F1 Team", "OCO"],
  [2022, race_list[4], "BWT Alpine F1 Team", "ALO"],
  [2022, race_list[4], "Scuderia AlphaTauri", "GAS"],
  [2022, race_list[4], "Scuderia AlphaTauri", "TSU"],
  [2022, race_list[4], "Aston Martin Aramco Cognizant F1 Team", "STR"],
  [2022, race_list[4], "Aston Martin Aramco Cognizant F1 Team", "VET"],
  [2022, race_list[4], "Williams Racing", "ALB"],
  [2022, race_list[4], "Williams Racing", "LAT"],
  [2022, race_list[4], "Alfa Romeo F1 Team Orlen", "BOT"],
  [2022, race_list[4], "Alfa Romeo F1 Team Orlen", "ZHO"],
  [2022, race_list[4], "Haas F1 Team", "MAG"],
  [2022, race_list[4], "Haas F1 Team", "MSC"],

  [2022, race_list[5], "Mercedes-AMG Petronas F1 Team", "HAM"],
  [2022, race_list[5], "Mercedes-AMG Petronas F1 Team", "RUS"],
  [2022, race_list[5], "Oracle Red Bull Racing", "VER"],
  [2022, race_list[5], "Oracle Red Bull Racing", "PER"],
  [2022, race_list[5], "Scuderia Ferrari", "LEC"],
  [2022, race_list[5], "Scuderia Ferrari", "SAI"],
  [2022, race_list[5], "McLaren F1 Team", "NOR"],
  [2022, race_list[5], "McLaren F1 Team", "RIC"],
  [2022, race_list[5], "BWT Alpine F1 Team", "OCO"],
  [2022, race_list[5], "BWT Alpine F1 Team", "ALO"],
  [2022, race_list[5], "Scuderia AlphaTauri", "GAS"],
  [2022, race_list[5], "Scuderia AlphaTauri", "TSU"],
  [2022, race_list[5], "Aston Martin Aramco Cognizant F1 Team", "STR"],
  [2022, race_list[5], "Aston Martin Aramco Cognizant F1 Team", "VET"],
  [2022, race_list[5], "Williams Racing", "ALB"],
  [2022, race_list[5], "Williams Racing", "LAT"],
  [2022, race_list[5], "Alfa Romeo F1 Team Orlen", "BOT"],
  [2022, race_list[5], "Alfa Romeo F1 Team Orlen", "ZHO"],
  [2022, race_list[5], "Haas F1 Team", "MAG"],
  [2022, race_list[5], "Haas F1 Team", "MSC"],

  [2022, race_list[6], "Mercedes-AMG Petronas F1 Team", "HAM"],
  [2022, race_list[6], "Mercedes-AMG Petronas F1 Team", "RUS"],
  [2022, race_list[6], "Oracle Red Bull Racing", "VER"],
  [2022, race_list[6], "Oracle Red Bull Racing", "PER"],
  [2022, race_list[6], "Scuderia Ferrari", "LEC"],
  [2022, race_list[6], "Scuderia Ferrari", "SAI"],
  [2022, race_list[6], "McLaren F1 Team", "NOR"],
  [2022, race_list[6], "McLaren F1 Team", "RIC"],
  [2022, race_list[6], "BWT Alpine F1 Team", "OCO"],
  [2022, race_list[6], "BWT Alpine F1 Team", "ALO"],
  [2022, race_list[6], "Scuderia AlphaTauri", "GAS"],
  [2022, race_list[6], "Scuderia AlphaTauri", "TSU"],
  [2022, race_list[6], "Aston Martin Aramco Cognizant F1 Team", "STR"],
  [2022, race_list[6], "Aston Martin Aramco Cognizant F1 Team", "VET"],
  [2022, race_list[6], "Williams Racing", "ALB"],
  [2022, race_list[6], "Williams Racing", "LAT"],
  [2022, race_list[6], "Alfa Romeo F1 Team Orlen", "BOT"],
  [2022, race_list[6], "Alfa Romeo F1 Team Orlen", "ZHO"],
  [2022, race_list[6], "Haas F1 Team", "MAG"],
  [2022, race_list[6], "Haas F1 Team", "MSC"],

  [2022, race_list[7], "Mercedes-AMG Petronas F1 Team", "HAM"],
  [2022, race_list[7], "Mercedes-AMG Petronas F1 Team", "RUS"],
  [2022, race_list[7], "Oracle Red Bull Racing", "VER"],
  [2022, race_list[7], "Oracle Red Bull Racing", "PER"],
  [2022, race_list[7], "Scuderia Ferrari", "LEC"],
  [2022, race_list[7], "Scuderia Ferrari", "SAI"],
  [2022, race_list[7], "McLaren F1 Team", "NOR"],
  [2022, race_list[7], "McLaren F1 Team", "RIC"],
  [2022, race_list[7], "BWT Alpine F1 Team", "OCO"],
  [2022, race_list[7], "BWT Alpine F1 Team", "ALO"],
  [2022, race_list[7], "Scuderia AlphaTauri", "GAS"],
  [2022, race_list[7], "Scuderia AlphaTauri", "TSU"],
  [2022, race_list[7], "Aston Martin Aramco Cognizant F1 Team", "STR"],
  [2022, race_list[7], "Aston Martin Aramco Cognizant F1 Team", "VET"],
  [2022, race_list[7], "Williams Racing", "ALB"],
  [2022, race_list[7], "Williams Racing", "LAT"],
  [2022, race_list[7], "Alfa Romeo F1 Team Orlen", "BOT"],
  [2022, race_list[7], "Alfa Romeo F1 Team Orlen", "ZHO"],
  [2022, race_list[7], "Haas F1 Team", "MAG"],
  [2022, race_list[7], "Haas F1 Team", "MSC"],

  [2022, race_list[8], "Mercedes-AMG Petronas F1 Team", "HAM"],
  [2022, race_list[8], "Mercedes-AMG Petronas F1 Team", "RUS"],
  [2022, race_list[8], "Oracle Red Bull Racing", "VER"],
  [2022, race_list[8], "Oracle Red Bull Racing", "PER"],
  [2022, race_list[8], "Scuderia Ferrari", "LEC"],
  [2022, race_list[8], "Scuderia Ferrari", "SAI"],
  [2022, race_list[8], "McLaren F1 Team", "NOR"],
  [2022, race_list[8], "McLaren F1 Team", "RIC"],
  [2022, race_list[8], "BWT Alpine F1 Team", "OCO"],
  [2022, race_list[8], "BWT Alpine F1 Team", "ALO"],
  [2022, race_list[8], "Scuderia AlphaTauri", "GAS"],
  [2022, race_list[8], "Scuderia AlphaTauri", "TSU"],
  [2022, race_list[8], "Aston Martin Aramco Cognizant F1 Team", "STR"],
  [2022, race_list[8], "Aston Martin Aramco Cognizant F1 Team", "VET"],
  [2022, race_list[8], "Williams Racing", "ALB"],
  [2022, race_list[8], "Williams Racing", "LAT"],
  [2022, race_list[8], "Alfa Romeo F1 Team Orlen", "BOT"],
  [2022, race_list[8], "Alfa Romeo F1 Team Orlen", "ZHO"],
  [2022, race_list[8], "Haas F1 Team", "MAG"],
  [2022, race_list[8], "Haas F1 Team", "MSC"],

  [2022, race_list[9], "Mercedes-AMG Petronas F1 Team", "HAM"],
  [2022, race_list[9], "Mercedes-AMG Petronas F1 Team", "RUS"],
  [2022, race_list[9], "Oracle Red Bull Racing", "VER"],
  [2022, race_list[9], "Oracle Red Bull Racing", "PER"],
  [2022, race_list[9], "Scuderia Ferrari", "LEC"],
  [2022, race_list[9], "Scuderia Ferrari", "SAI"],
  [2022, race_list[9], "McLaren F1 Team", "NOR"],
  [2022, race_list[9], "McLaren F1 Team", "RIC"],
  [2022, race_list[9], "BWT Alpine F1 Team", "OCO"],
  [2022, race_list[9], "BWT Alpine F1 Team", "ALO"],
  [2022, race_list[9], "Scuderia AlphaTauri", "GAS"],
  [2022, race_list[9], "Scuderia AlphaTauri", "TSU"],
  [2022, race_list[9], "Aston Martin Aramco Cognizant F1 Team", "STR"],
  [2022, race_list[9], "Aston Martin Aramco Cognizant F1 Team", "VET"],
  [2022, race_list[9], "Williams Racing", "ALB"],
  [2022, race_list[9], "Williams Racing", "LAT"],
  [2022, race_list[9], "Alfa Romeo F1 Team Orlen", "BOT"],
  [2022, race_list[9], "Alfa Romeo F1 Team Orlen", "ZHO"],
  [2022, race_list[9], "Haas F1 Team", "MAG"],
  [2022, race_list[9], "Haas F1 Team", "MSC"]
]

race_drivers_list.each do |details|
  RaceDriver.create(race: Race.where(season: Season.where(year: details[0]).first, name: details[1]).first, team_driver: TeamDriver.where(constructor: Constructor.where(name: details[2]), driver: Driver.where(code: details[3])).first)
end
