lock_choices:
  cron: "0 22 * * 5"
  class: "LockChoicesJob"

randomize_unchosen_choices:
  cron: "1 22 * * 5"
  class: "RandomizeUnchosenChoicesJob"

lock_previous_race_choices:
  cron: "59 23 * * 5"
  class: "LockPreviousRaceChoicesJob"
